id: 195
name: cbSettingSegmentType
description: ''
category: a_cb_settings
properties: 'a:0:{}'

-----

No segment (disables all settings below)=
Basic segment (borderless, but with padding)=basic
Regular segment (with border and padding)=regular
Raised segment (slightly more emphasised)=raised
Vertical segment (create a vertical group)=vertical